### ISSUE TITLE
HomeBridge Plugin?

### ISSUE THREAD

**Issue by dsully** [sean9keenan/BigAssFansAPI#1]
Any plans to make a HomeBridge plugin?

**Comment by sean9keenan** [comment]
Actually yes - hopefully will get around to it before iOS 10 comes out 👍

**Comment by pedroserano** [comment]
👍 +1 for HomeKit

**Comment by sean9keenan** [comment]
Got around to doing this over the weekend, [threw it up here](https://github.com/sean9keenan/homebridge-bigAssFans)!
