### ISSUE TITLE
Get current temp

### ISSUE THREAD

**Issue by jabbera** [sean9keenan/BigAssFansAPI#4]
Is there an Api for getting the current temperature in the room?

**Comment by sean9keenan** [comment]
Unfortunately not that I know of - only API's to set the fan to do certain things at certain temperature thresholds. This may be different for the L-Series fans however

**Comment by jabbera** [comment]
Thanks. This is a huge bummer. I've been looking for something that goes in each room that is a combination environment/motion sensor that is hard wired. (Either smoke detector, light fixture, etc) something with a high Wife Acceptance Factor. I thought this might be it.

**Comment by sean9keenan** [comment]
It might have been added in a recent firmware update - since they definitely have temp sensors on there. If they show up I'll let you know in this thread 👍

**Comment by pedroserano** [comment]
Likewise I have not seen it exposed in the API for the L series, but I certainly haven't explored it completely.
