### ISSUE TITLE
trouble with multiple fans

### ISSUE THREAD

**Issue by epahogan** [sean9keenan/BigAssFansAPI#7]
I have 2 fans (fanA, fanB) listed in the config.json's accessories array. If I change the config.json to pick just one fan (either fanA or fanB)it works fine; but it fails if the array has 2 elements.

I suspect that I just need to have it pick a second port for the second fan, but not sure where to make that change to the code.

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 0.0.0.0:31415
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at dgram.js:221:18
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

**Comment by epahogan** [comment]
I forced the second fan to pick use different port and that got past the initialization error, but the device is not responsive on the Home app. So they both need to use that same port and get past the EADDRINUSE error.

**Comment by epahogan** [comment]
I should have mentioned that I'm trying to integrate this with homebridge and adding each of the two fans as separate accessories in the home bridge config.json.

Homebridge seems to call the FanMaster function with numberOfExpectedFans=0 twice, rather than calling it once with numberOfExpectedFans=2.

**Comment by sean9keenan** [comment]
Yeah, unfortunately the config doesn't work with multiple accessories - the "solution" is to use the new config format: 

```
    "platforms": [
        {
            "platform": "BigAssFans",
            "name": "Big Ass Fan"
        }
    ]
```

This properly does the full scan for all fans on your network and adds them. It does have the drawback of not being able to individually change some of the fans the same way you can with the "legacy" format I have in the [readme](https://github.com/sean9keenan/homebridge-bigAssFans/blob/master/README.md).

That's on my todo list, but this project has recently been on the back burner for me. PR's are welcome! Do you need any of the customization offered by the legacy format, or could you rely on just the scan?
